msg_1=Userlogs
href_1=/administration/useractivitylog/list.action
token_1=always.allowed

msg_2=settings.Mailloop
href_2=/administration/bounce/list.action
token_2=mailloop.show

msg_3=UserActivitylog.Users
href_3=/admin/list.action?restoreSearchParams=true
token_3=admin.show

msg_4=mailloop.inbox
href_4=/response-inbox.action
token_4=inbox.show
conditionId_4=responseInboxCondition

msg_5=settings.Usergroups
href_5=/administration/usergroup/list.action
token_5=role.show

msg_6=CompanyAdmin
href_6=
token_6=always.disallowed
upsellingRef_6=clients_upselling

msg_7=settings.server.status
href_7=/serverstatus/view.action
token_7=server.status

navigation.plugin=emm_core_navigation
navigation.extensionpoint=navigation.administration