#!/bin/sh
#
. $HOME/scripts/config.sh
#
if [ $# -ne 3 ]; then
	echo "Usage: $0 <domain> <selector> <length>"
	exit 1
fi
domain="$1"
selector="$2"
length="$3"
base="${selector}@${domain}"
priv="${base}.priv"
pub="${base}.pub"
if [ -f "$priv" ] || [ -f "$pub" ]; then
	echo "Either $priv or $pub already exists, aborting"
	exit 1
fi
#
echo "Creating private/public key pair $priv/$pub for $domain (selector $selector) with $length bit"
dkim-mgr -n "$priv" "$pub" "$length"
if [ $? -ne 0 ]; then
	echo "Failed to create keys, aborting"
	exit 1
fi
#
echo "Installation sample for your DNS:"
echo "${selector}._domainkey.${domain}. IN TXT \"v=DKIM1; p=`dkim-mgr -D $pub`\""
#
todo="install-${base}.sh"
echo -n "Creating $todo .. "
cat << '__EOF__' > $todo
#!/bin/sh
#
. $HOME/scripts/config.sh
#
__EOF__
#
echo -n "add "
echo "dkim-mgr -v -c 1 \"\$@\" $domain $selector $priv" >> $todo
chmod 755 $todo
echo "done."

