#!/bin/sh
####################################################################################################################################################################################################################################################################
#                                                                                                                                                                                                                                                                  #
#                                                                                                                                                                                                                                                                  #
#        Copyright (C) 2025 AGNITAS AG (https://www.agnitas.org)                                                                                                                                                                                                   #
#                                                                                                                                                                                                                                                                  #
#        This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.    #
#        This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.           #
#        You should have received a copy of the GNU Affero General Public License along with this program. If not, see <https://www.gnu.org/licenses/>.                                                                                                            #
#                                                                                                                                                                                                                                                                  #
####################################################################################################################################################################################################################################################################
#
. $HOME/scripts/config.sh
#
if [ $# -ne 3 ]; then
	echo "Usage: $0 <domain> <selector> <length>"
	exit 1
fi
domain="$1"
selector="$2"
length="$3"
base="${selector}@${domain}"
priv="${base}.priv"
pub="${base}.pub"
if [ -f "$priv" ] || [ -f "$pub" ]; then
	echo "Either $priv or $pub already exists, aborting"
	exit 1
fi
#
echo "Creating private/public key pair $priv/$pub for $domain (selector $selector) with $length bit"
dkim-mgr -n "$priv" "$pub" "$length"
if [ $? -ne 0 ]; then
	echo "Failed to create keys, aborting"
	exit 1
fi
#
echo "Installation sample for your DNS:"
echo "${selector}._domainkey.${domain}. IN TXT \"v=DKIM1; p=`dkim-mgr -D $pub`\""
#
todo="install-${base}.sh"
echo -n "Creating $todo .. "
cat << '__EOF__' > $todo
#!/bin/sh
#
. $HOME/scripts/config.sh
#
__EOF__
#
echo -n "add "
echo "dkim-mgr -v -c 1 \"\$@\" $domain $selector $priv" >> $todo
chmod 755 $todo
echo "done."

