DELETE FROM admin_to_group_tbl WHERE admin_id = 1 AND admin_group_id = 1;
INSERT INTO admin_to_group_tbl (admin_id, admin_group_id) VALUES (1, 1);

-- Admin group: OpenEMM
DELETE FROM admin_group_permission_tbl WHERE admin_group_id IN (SELECT admin_group_id FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'actions.change' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'actions.delete' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'actions.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'admin.change' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'admin.delete' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'admin.new' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'admin.sendWelcome' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'admin.setgroup' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'admin.setpermission' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'admin.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'adminlog.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'blacklist' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'calendar.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'campaign.change' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'campaign.delete' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'campaign.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'charset.use.iso_8859_15' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'charset.use.utf_8' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'datasource.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'export.change' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'export.delete' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'forms.change' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'forms.delete' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'forms.import' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'forms.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'import.change' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'import.delete' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'import.mode.add' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'import.mode.add_update' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'import.mode.blacklist' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'import.mode.bounce' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'import.mode.doublechecking' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'import.mode.duplicates' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'import.mode.only_update' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'import.mode.unsubscribe' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'mailing.attachments.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'mailing.can_send_always' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'mailing.change' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'mailing.classic' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'mailing.components.change' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'mailing.components.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'mailing.content.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'mailing.delete' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'mailing.extend_trackable_links' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'mailing.import' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'mailing.send.admin.options' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'mailing.send.admin.target' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'mailing.send.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'mailing.send.world' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'mailing.setmaxrecipients' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'mailing.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'mailing.show.types' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'mailinglist.change' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'mailinglist.delete' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'mailinglist.recipients.delete' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'mailinglist.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'mailloop.change' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'mailloop.delete' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'mailloop.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'mediatype.email' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'profileField.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'profileField.visible' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'recipient.change' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'recipient.change.bulk' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'recipient.create' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'recipient.delete' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'recipient.gender.extended' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'recipient.history' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'recipient.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'report.birt.change' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'report.birt.delete' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'report.birt.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'role.change' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'role.delete' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'role.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'salutation.change' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'salutation.delete' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'salutation.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'server.status' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'statistic.softbounces.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'stats.domains' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'stats.ecs' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'stats.mailing' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'stats.month' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'stats.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'stats.userform' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'targets.change' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'targets.delete' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'targets.lock' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'targets.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'template.change' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'template.delete' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'template.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'webservice.user.change' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'webservice.user.create' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'webservice.user.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'wizard.export' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'wizard.import' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'wizard.importclassic' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'workflow.activate' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'workflow.delete' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'workflow.change' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'workflow.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'forms.export' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'mailing.export' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'restfulUser.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'restfulUser.new' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'restfulUser.change' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'restfulUser.delete' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'settings.extended' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, permission_name) (SELECT admin_group_id, 'mailinglists.addresses' FROM admin_group_tbl WHERE shortname = 'OpenEMM');

-- User/Admin: EMM-Master
DELETE FROM admin_permission_tbl WHERE admin_id = 1;
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'actions.change');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'actions.delete');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'actions.show');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'admin.change');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'admin.delete');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'admin.new');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'admin.sendWelcome');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'admin.setgroup');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'admin.setpermission');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'admin.show');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'adminlog.show');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'blacklist');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'calendar.show');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'campaign.change');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'campaign.delete');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'campaign.show');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'charset.use.iso_8859_15');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'charset.use.utf_8');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'datasource.show');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'export.change');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'export.delete');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'forms.change');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'forms.delete');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'forms.import');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'forms.show');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'import.change');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUEs (1, 'import.delete');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'import.mode.add');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'import.mode.add_update');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'import.mode.blacklist');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'import.mode.bounce');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'import.mode.doublechecking');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'import.mode.duplicates');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'import.mode.only_update');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'import.mode.unsubscribe');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'mailing.attachments.show');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'mailing.can_send_always');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'mailing.change');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'mailing.classic');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'mailing.components.change');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'mailing.components.show');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'mailing.content.show');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'mailing.delete');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'mailing.extend_trackable_links');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'mailing.import');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'mailing.recipients.show');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'mailing.send.admin.options');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'mailing.send.admin.target');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'mailing.send.show');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'mailing.send.world');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'mailing.setmaxrecipients');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'mailing.show');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'mailing.show.types');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'mailinglist.change');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'mailinglist.delete');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'mailinglist.recipients.delete');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'mailinglist.show');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'mailloop.change');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'mailloop.delete');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'mailloop.show');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'mediatype.email');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'profileField.show');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'profileField.visible');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'recipient.change');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'recipient.change.bulk');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'recipient.create');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'recipient.delete');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'recipient.gender.extended');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'recipient.history');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'recipient.show');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'role.change');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'role.delete');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'role.show');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'salutation.change');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'salutation.delete');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'salutation.show');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'server.status');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'statistic.softbounces.show');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'stats.domains');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'stats.ecs');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'stats.mailing');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'stats.month');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'stats.show');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'stats.userform');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'targets.change');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'targets.delete');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'targets.lock');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'targets.show');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'template.change');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'template.delete');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'template.show');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'webservice.user.change');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'webservice.user.create');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'webservice.user.show');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'wizard.export');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'wizard.import');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'wizard.importclassic');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'workflow.activate');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'workflow.delete');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'workflow.change');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'workflow.show');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'forms.export');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'mailing.export');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'restfulUser.show');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'restfulUser.new');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'restfulUser.change');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'restfulUser.delete');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'settings.extended');
INSERT INTO admin_permission_tbl (admin_id, permission_name) VALUES (1, 'mailinglists.addresses');
