-- OPEN-279

DELETE FROM admin_group_tbl WHERE admin_group_id = 1;
INSERT INTO admin_group_tbl (admin_group_id, company_id, shortname, description) VALUES (1, 1, 'OpenEMM', 'OpenEMM');

-- Admin group: OpenEMM
DELETE FROM admin_group_permission_tbl WHERE admin_group_id IN (SELECT admin_group_id FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'action.op.ActivateDoubleOptIn' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'action.op.ContentView' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'action.op.ExecuteScript' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'action.op.GetArchiveList' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'action.op.GetArchiveMailing' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'action.op.GetCustomer' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'action.op.IdentifyCustomer' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'action.op.SendMailing' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'action.op.ServiceMail' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'action.op.SubscribeCustomer' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'action.op.UnsubscribeCustomer' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'action.op.UpdateCustomer' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'actions.change' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'actions.delete' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'actions.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'admin.change' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'admin.delete' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'admin.new' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'admin.password.once' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'admin.setgroup' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'admin.setpermission' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'admin.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'adminlog.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'blacklist' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'calendar.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'campaign.change' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'campaign.delete' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'campaign.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'charset.use.iso_8859_15' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'charset.use.utf_8' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'content_tab_migration' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'forms.change' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'forms.delete' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'forms.import' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'forms.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'import.mailinglist.without' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'import.mode.add' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'import.mode.add_update' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'import.mode.blacklist' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'import.mode.bounce' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'import.mode.bouncereactivate' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'import.mode.doublechecking' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'import.mode.duplicates' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'import.mode.null_values' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'import.mode.only_update' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'import.mode.unsubscribe' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'mailing.attachments.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'mailing.can_send_always' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'mailing.change' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'mailing.column.targetgroups' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'mailing.components.change' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'mailing.components.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'mailing.content.change.always' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'mailing.content.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'mailing.content.showExcludedTargetgroups' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'mailing.copy' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'mailing.default_action' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'mailing.delete' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'mailing.doublechecking' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'mailing.envelope_address' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'mailing.expire' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'mailing.extend_trackable_links' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'mailing.graphics_upload' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'mailing.graphics_upload_archive' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'mailing.import' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'mailing.needstarget' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'mailing.new' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'mailing.send.admin' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'mailing.send.admin.options' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'mailing.send.admin.target' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'mailing.send.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'mailing.send.status.email' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'mailing.send.test' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'mailing.send.world' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'mailing.setmaxrecipients' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'mailing.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'mailing.show.charsets' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'mailing.show.types' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'mailing.target.calculate' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'mailinglist.change' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'mailinglist.delete' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'mailinglist.new' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'mailinglist.recipients.delete' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'mailinglist.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'mailloop.change' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'mailloop.delete' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'mailloop.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'mediatype.email' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'pluginmanager.change' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'pluginmanager.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'profileField.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'profileField.sort' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'profileField.visible' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'recipient.change' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'recipient.change.bulk' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'recipient.create' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'recipient.delete' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'recipient.gender.extended' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'recipient.history' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'recipient.list' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'recipient.profileField.html.allowed' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'recipient.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'recipient.tracking.veto' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'role.change' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'role.delete' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'role.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'salutation.change' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'salutation.delete' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'salutation.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'server.status' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'settings.open' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'statistic.individual.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'statistic.load.specific' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'statistic.softbounces.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'stats.domains' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'stats.ecs' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'stats.mailing' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'stats.month' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'stats.rdir' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'stats.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'stats.userform' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'targets.change' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'targets.createml' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'targets.delete' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'targets.eql.edit' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'targets.lock' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'targets.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'template.change' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'template.delete' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'template.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'update.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'userlog.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'user.xpress' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'webservice.user.change' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'webservice.user.create' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'webservice.user.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'wizard.export' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'wizard.import' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'wizard.importclassic' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'workflow.activate' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'workflow.delete' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'workflow.edit' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token) (SELECT admin_group_id, 'workflow.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');

-- User/Admin: EMM-Master
DELETE FROM admin_permission_tbl WHERE admin_id = 1;
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'action.op.ActivateDoubleOptIn');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'action.op.ContentView');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'action.op.ExecuteScript');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'action.op.GetArchiveList');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'action.op.GetArchiveMailing');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'action.op.GetCustomer');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'action.op.IdentifyCustomer');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'action.op.SendMailing');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'action.op.ServiceMail');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'action.op.SubscribeCustomer');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'action.op.UnsubscribeCustomer');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'action.op.UpdateCustomer');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'actions.change');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'actions.delete');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'actions.show');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'admin.change');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'admin.delete');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'admin.new');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'admin.password.once');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'admin.setgroup');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'admin.setpermission');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'admin.show');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'adminlog.show');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'blacklist');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'calendar.show');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'campaign.change');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'campaign.delete');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'campaign.show');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'charset.use.iso_8859_15');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'charset.use.utf_8');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'content_tab_migration');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'forms.change');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'forms.delete');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'forms.import');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'forms.show');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'import.mailinglist.without');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'import.mode.add');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'import.mode.add_update');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'import.mode.blacklist');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'import.mode.bounce');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'import.mode.bouncereactivate');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'import.mode.doublechecking');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'import.mode.duplicates');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'import.mode.null_values');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'import.mode.only_update');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'import.mode.unsubscribe');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'mailing.attachments.show');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'mailing.can_send_always');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'mailing.change');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'mailing.column.targetgroups');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'mailing.components.change');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'mailing.components.show');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'mailing.content.change.always');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'mailing.content.show');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'mailing.content.showExcludedTargetgroups');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'mailing.copy');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'mailing.default_action');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'mailing.delete');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'mailing.doublechecking');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'mailing.envelope_address');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'mailing.expire');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'mailing.extend_trackable_links');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'mailing.graphics_upload');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'mailing.graphics_upload_archive');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'mailing.import');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'mailing.needstarget');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'mailing.new');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'mailing.send.admin');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'mailing.send.admin.options');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'mailing.send.admin.target');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'mailing.send.show');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'mailing.send.status.email');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'mailing.send.test');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'mailing.send.world');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'mailing.setmaxrecipients');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'mailing.show');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'mailing.show.charsets');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'mailing.show.types');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'mailing.target.calculate');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'mailinglist.change');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'mailinglist.delete');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'mailinglist.new');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'mailinglist.recipients.delete');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'mailinglist.show');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'mailloop.change');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'mailloop.delete');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'mailloop.show');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'mediatype.email');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'pluginmanager.change');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'pluginmanager.show');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'profileField.show');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'profileField.sort');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'profileField.visible');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'recipient.change');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'recipient.change.bulk');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'recipient.create');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'recipient.delete');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'recipient.gender.extended');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'recipient.history');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'recipient.list');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'recipient.profileField.html.allowed');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'recipient.show');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'recipient.tracking.veto');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'role.change');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'role.delete');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'role.show');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'salutation.change');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'salutation.delete');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'salutation.show');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'server.status');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'settings.open');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'statistic.individual.show');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'statistic.load.specific');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'statistic.softbounces.show');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'stats.domains');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'stats.ecs');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'stats.mailing');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'stats.month');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'stats.rdir');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'stats.show');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'stats.userform');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'targets.change');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'targets.createml');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'targets.delete');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'targets.eql.edit');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'targets.lock');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'targets.show');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'template.change');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'template.delete');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'template.show');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'update.show');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'userlog.show');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'user.xpress');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'webservice.user.change');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'webservice.user.create');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'webservice.user.show');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'wizard.export');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'wizard.import');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'wizard.importclassic');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'workflow.activate');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'workflow.delete');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'workflow.edit');
INSERT INTO admin_permission_tbl (admin_id, security_token) VALUES (1, 'workflow.show');
