UPDATE admin_tbl SET admin_group_id = 1 WHERE username = 'emm-master';
DELETE FROM admin_to_group_tbl WHERE admin_id = 1 AND admin_group_id = 1;
INSERT INTO admin_to_group_tbl (admin_id, admin_group_id) VALUES (1, 1);

-- Admin group: OpenEMM
DELETE FROM admin_group_permission_tbl WHERE admin_group_id IN (SELECT admin_group_id FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'actions.change', 'actions.change' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'actions.delete', 'actions.delete' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'actions.show', 'actions.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'admin.change', 'admin.change' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'admin.delete', 'admin.delete' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'admin.new', 'admin.new' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'admin.setgroup', 'admin.setgroup' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'admin.setpermission', 'admin.setpermission' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'admin.show', 'admin.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'adminlog.show', 'adminlog.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'blacklist', 'blacklist' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'calendar.show', 'calendar.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'campaign.autoopt', 'campaign.autoopt' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'campaign.change', 'campaign.change' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'campaign.delete', 'campaign.delete' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'campaign.show', 'campaign.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'charset.use.iso_8859_15', 'charset.use.iso_8859_15' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'charset.use.utf_8', 'charset.use.utf_8' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'forms.change', 'forms.change' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'forms.delete', 'forms.delete' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'forms.import', 'forms.import' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'forms.show', 'forms.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'import.mode.add', 'import.mode.add' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'import.mode.add_update', 'import.mode.add_update' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'import.mode.blacklist', 'import.mode.blacklist' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'import.mode.bounce', 'import.mode.bounce' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'import.mode.doublechecking', 'import.mode.doublechecking' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'import.mode.duplicates', 'import.mode.duplicates' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'import.mode.only_update', 'import.mode.only_update' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'import.mode.unsubscribe', 'import.mode.unsubscribe' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'mailing.attachments.show', 'mailing.attachments.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'mailing.can_send_always', 'mailing.can_send_always' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'mailing.change', 'mailing.change' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'mailing.components.change', 'mailing.components.change' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'mailing.components.show', 'mailing.components.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'mailing.content.show', 'mailing.content.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'mailing.content.showExcludedTargetgroups', 'mailing.content.showExcludedTargetgroups' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'mailing.delete', 'mailing.delete' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'mailing.envelope_address', 'mailing.envelope_address' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'mailing.extend_trackable_links', 'mailing.extend_trackable_links' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'mailing.import', 'mailing.import' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'mailing.send.admin.options', 'mailing.send.admin.options' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'mailing.send.admin.target', 'mailing.send.admin.target' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'mailing.send.show', 'mailing.send.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'mailing.send.world', 'mailing.send.world' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'mailing.setmaxrecipients', 'mailing.setmaxrecipients' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'mailing.show', 'mailing.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'mailing.show.types', 'mailing.show.types' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'mailinglist.change', 'mailinglist.change' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'mailinglist.delete', 'mailinglist.delete' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'mailinglist.recipients.delete', 'mailinglist.recipients.delete' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'mailinglist.show', 'mailinglist.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'mailloop.change', 'mailloop.change' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'mailloop.delete', 'mailloop.delete' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'mailloop.show', 'mailloop.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'mediatype.email', 'mediatype.email' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'profileField.show', 'profileField.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'profileField.visible', 'profileField.visible' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'recipient.change', 'recipient.change' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'recipient.change.bulk', 'recipient.change.bulk' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'recipient.create', 'recipient.create' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'recipient.delete', 'recipient.delete' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'recipient.gender.extended', 'recipient.gender.extended' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'recipient.history', 'recipient.history' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'recipient.show', 'recipient.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'recipient.tracking.veto', 'recipient.tracking.veto' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'role.change', 'role.change' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'role.delete', 'role.delete' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'role.show', 'role.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'salutation.change', 'salutation.change' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'salutation.delete', 'salutation.delete' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'salutation.show', 'salutation.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'server.status', 'server.status' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'statistic.load.specific', 'statistic.load.specific' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'statistic.softbounces.show', 'statistic.softbounces.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'stats.domains', 'stats.domains' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'stats.ecs', 'stats.ecs' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'stats.mailing', 'stats.mailing' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'stats.month', 'stats.month' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'stats.show', 'stats.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'stats.userform', 'stats.userform' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'targets.change', 'targets.change' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'targets.createml', 'targets.createml' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'targets.delete', 'targets.delete' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'targets.lock', 'targets.lock' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'targets.show', 'targets.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'template.change', 'template.change' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'template.delete', 'template.delete' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'template.show', 'template.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'user.xpress', 'user.xpress' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'webservice.user.change', 'webservice.user.change' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'webservice.user.create', 'webservice.user.create' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'webservice.user.show', 'webservice.user.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'wizard.export', 'wizard.export' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'wizard.import', 'wizard.import' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'wizard.importclassic', 'wizard.importclassic' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'workflow.activate', 'workflow.activate' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'workflow.delete', 'workflow.delete' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'workflow.change', 'workflow.change' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'workflow.show', 'workflow.show' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'forms.export', 'forms.export' FROM admin_group_tbl WHERE shortname = 'OpenEMM');
INSERT INTO admin_group_permission_tbl (admin_group_id, security_token, permission_name) (SELECT admin_group_id, 'mailing.export', 'mailing.export' FROM admin_group_tbl WHERE shortname = 'OpenEMM');


-- User/Admin: EMM-Master
DELETE FROM admin_permission_tbl WHERE admin_id = 1;
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'actions.change', 'actions.change');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'actions.delete', 'actions.delete');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'actions.show', 'actions.show');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'admin.change', 'admin.change');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'admin.delete', 'admin.delete');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'admin.new', 'admin.new');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'admin.setgroup', 'admin.setgroup');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'admin.setpermission', 'admin.setpermission');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'admin.show', 'admin.show');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'adminlog.show', 'adminlog.show');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'blacklist', 'blacklist');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'calendar.show', 'calendar.show');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'campaign.autoopt', 'campaign.autoopt');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'campaign.change', 'campaign.change');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'campaign.delete', 'campaign.delete');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'campaign.show', 'campaign.show');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'charset.use.iso_8859_15', 'charset.use.iso_8859_15');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'charset.use.utf_8', 'charset.use.utf_8');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'forms.change', 'forms.change');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'forms.delete', 'forms.delete');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'forms.import', 'forms.import');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'forms.show', 'forms.show');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'import.mode.add', 'import.mode.add');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'import.mode.add_update', 'import.mode.add_update');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'import.mode.blacklist', 'import.mode.blacklist');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'import.mode.bounce', 'import.mode.bounce');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'import.mode.doublechecking', 'import.mode.doublechecking');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'import.mode.duplicates', 'import.mode.duplicates');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'import.mode.only_update', 'import.mode.only_update');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'import.mode.unsubscribe', 'import.mode.unsubscribe');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'mailing.attachments.show', 'mailing.attachments.show');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'mailing.can_send_always', 'mailing.can_send_always');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'mailing.change', 'mailing.change');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'mailing.components.change', 'mailing.components.change');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'mailing.components.show', 'mailing.components.show');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'mailing.content.show', 'mailing.content.show');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'mailing.content.showExcludedTargetgroups', 'mailing.content.showExcludedTargetgroups');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'mailing.delete', 'mailing.delete');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'mailing.envelope_address', 'mailing.envelope_address');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'mailing.extend_trackable_links', 'mailing.extend_trackable_links');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'mailing.import', 'mailing.import');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'mailing.send.admin.options', 'mailing.send.admin.options');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'mailing.send.admin.target', 'mailing.send.admin.target');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'mailing.send.show', 'mailing.send.show');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'mailing.send.world', 'mailing.send.world');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'mailing.setmaxrecipients', 'mailing.setmaxrecipients');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'mailing.show', 'mailing.show');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'mailing.show.types', 'mailing.show.types');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'mailinglist.change', 'mailinglist.change');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'mailinglist.delete', 'mailinglist.delete');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'mailinglist.recipients.delete', 'mailinglist.recipients.delete');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'mailinglist.show', 'mailinglist.show');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'mailloop.change', 'mailloop.change');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'mailloop.delete', 'mailloop.delete');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'mailloop.show', 'mailloop.show');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'mediatype.email', 'mediatype.email');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'profileField.show', 'profileField.show');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'profileField.visible', 'profileField.visible');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'recipient.change', 'recipient.change');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'recipient.change.bulk', 'recipient.change.bulk');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'recipient.create', 'recipient.create');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'recipient.delete', 'recipient.delete');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'recipient.gender.extended', 'recipient.gender.extended');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'recipient.history', 'recipient.history');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'recipient.show', 'recipient.show');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'recipient.tracking.veto', 'recipient.tracking.veto');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'role.change', 'role.change');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'role.delete', 'role.delete');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'role.show', 'role.show');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'salutation.change', 'salutation.change');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'salutation.delete', 'salutation.delete');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'salutation.show', 'salutation.show');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'server.status', 'server.status');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'statistic.load.specific', 'statistic.load.specific');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'statistic.softbounces.show', 'statistic.softbounces.show');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'stats.domains', 'stats.domains');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'stats.ecs', 'stats.ecs');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'stats.mailing', 'stats.mailing');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'stats.month', 'stats.month');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'stats.show', 'stats.show');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'stats.userform', 'stats.userform');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'targets.change', 'targets.change');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'targets.createml', 'targets.createml');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'targets.delete', 'targets.delete');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'targets.lock', 'targets.lock');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'targets.show', 'targets.show');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'template.change', 'template.change');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'template.delete', 'template.delete');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'template.show', 'template.show');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'user.xpress', 'user.xpress');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'webservice.user.change', 'webservice.user.change');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'webservice.user.create', 'webservice.user.create');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'webservice.user.show', 'webservice.user.show');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'wizard.export', 'wizard.export');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'wizard.import', 'wizard.import');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'wizard.importclassic', 'wizard.importclassic');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'workflow.activate', 'workflow.activate');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'workflow.delete', 'workflow.delete');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'workflow.change', 'workflow.change');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'workflow.show', 'workflow.show');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'forms.export', 'forms.export');
INSERT INTO admin_permission_tbl (admin_id, security_token, permission_name) VALUES (1, 'mailing.export', 'mailing.export');
